### PR TITLE
Multiple translation additions / corrections

### PR DESCRIPTION
**Pull request by KY4U**

### CODE REVIEW

**Comment by patrickebates** [comment]
Thanks for these updates.  Was looking over the changes to the translation logging.  Looks like most of them are for readability?  Also, prompted us to look at the hard-coded path for the log and consider some more options.

**Comment by KY4U** [comment]
Good morning.  The logging changes such as the addition of datetime stamp and error code help to match up transactions with the error log.  All other changes either fix a problem with a current translation, or it addresses new (required) translations.  I’ve been running this translation script on 4 sites and found no errors in the php_errors.log file.

I do have one question.  Why would you not attempt to translate all queries that generated SQL errors.  At present there are a dozen or so error codes that you look for and translate just those queries.  I’ve added a couple new error codes to process but it appears to me that the error codes are often irrelevant to what could be causing the error.  I’ve added some code to send a message to the error log if a sql error occurs and a translation is not performed due to an undefined error code.

**Comment by patrickebates** [comment]
During our initial testing of the translation layer, we determined that most errors would always be errors.  The statement didn't need translation, it was genuinely bad.  That was almost two years ago, and we've added a couple of codes since then ourselves.  So it may be that the process has matured to the point that filtering error codes is no longer necessary.  It's definitely worth looking into.

**Comment by patrickebates** [comment]
Also, I plan to merge this in over the weekend and make some updates to the location of the translation log.  It will then be placed alongside the php_error.log based on settings from the PHP environment.

WP 4.5.3 is expected next week, so your updates will ship along with our merge for that.

**Comment by KY4U** [comment]
Sounds great.  When I was tweaking the placement of the log and translation files, it occurred to me that having those locations in environment variables would be the next logical step.

**Comment by patrickebates** [comment]
`error_log( $endtransmsg, 3, dirname( getenv('error_log') ) . '\translate.log' );`

That's my current plan.  Get the folder of the PHP error log and write to the same location.

**Pull request merged**
