### PR TITLE
Refactor $wpdb->_insert_replace_helper to use MERGE instead of REPLACE 

### LINKED ISSUE #105: $wpdb->replace
Got another query issue here.

Woocommerce uses $wpdb->replace in its includes/class-wc-session-handler.php save_data() function.  Checking their readme, they did this "Tweak" in version 2.5.3 on 1/3/16, so it's fairly new.

This is resulting in an unsupported REPLACE INTO query like:

`REPLACE INTO [wp_woocommerce_sessions] ([session_key], [session_value], [session_expiry]) VALUES (...)`

digging around, looks like _insert_replace_helper needs to be refactored to check for existence first, then do an update or insert.

I'm assuming this isn't the only plugin in the world that uses this wp api and since it is using an actual wp api and not an inline query, I'm assuming this is something you guys want to have handled in your port and not at the translations level.

Looks like this isn't a super straightforward problem to solve though, especially since the replace api doesn't separate the key/id field out so you can do a proper "update where".

I'm seeing the general solution to be something like (not a php guy, so bare with me here):

`function _insert_replace_helper( $table, $data, $format = null, $type = 'INSERT' ) {
		$this->insert_id = 0;

		if ( ! in_array( strtoupper( $type ), array( 'REPLACE', 'INSERT' ) ) ) {
			return false;
		}

		$data2 = $this->process_fields( $table, $data, $format );
		if ( false === $data ) {
			return false;
		}
	
	if ($type === 'REPLACE') {
        //Get the primary key for the table, this assumes just a single primary key col, so not too robust.
		$keyColQuery = 'SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
						WHERE TABLE_NAME LIKE \'$table\' AND CONSTRAINT_NAME LIKE \'PK%\'';
		this->query($keyColQuery);
		$keyName = this->lastResult[0]->COLUMN_NAME;		
		
		//Use the incoming data as the conditions for the select query
		$conditions = array();
		foreach ( $data2 as $field => $value ) {
			$conditions[] = "[$field] = " . $value['format'];
		}
		$conditions = implode( ' AND ', $conditions );
		
		//get the primary key value, if the records exists
		$select = 'select $keyName from $table $conditions';
		this->query($select);
		
		if (this->last_result === null) {
		   //INSERT CASE, HANDLED BELOW
		} else {
			//found a record, so get the key value then
			//do UPDATE with original values + where condition				
			$keyValue = this->last_result[0]->$keyName; 
			$where = array($keyName, $keyValue);
			return update($table, $data, $where, $format);
	   }
	}
	//INSERT
	$formats = $values = array();
	foreach ( $data2 as $value ) {
		$formats[] = $value['format'];
		$values[]  = $value['value'];
	}

	$fields  = '[' . implode( '], [', array_keys( $data ) ) . ']';
	$formats = implode( ', ', $formats );

	$sql = "$type INTO [$table] ($fields) VALUES ($formats)";

	$this->check_current_query = false;
	return $this->query( $this->prepare( $sql, $values ) );
}`

It's not perfect because it doesn't handle complex keys, but something like that should get the job done.  I don't have a test server set up at the moment, so maybe one of you guys can peek at this and see if it passes muster.  A little more code and we could grab all the key cols, ordered correctly, and use that in the where, but I'm out of time for today.

Thoughts?

### PR DESCRIPTION
**Pull request by erikest**
This commit closes #105 by changing the generated SQL in the wpdb class's _insert_replace_helper function 

- from MySQL's REPLACE INTO 

- to a MERGE INTO statement which INSERTS or UPDATES depending on a matching row being found in the specified table.

### CODE REVIEW

**Comment by erikest** [comment]
There we go, forgot to commit to my local first, whoops :)

**Comment by erikest** [comment]
Hmm, already rethinking this...  I guess I was a little hasty in my refactor.  The problem I see in my code is that, it will never match after the first insert, since if the desire is an update, then it won't find the fields, since the field values are necessarily different than those in the database.  Seems so obvious now that I _think_ about it.  Looking at the REPLACE semantics for MySQL, it looks like the only way to reliably handle this is to get column info for each of the incoming fields, identify a primary key or unique index among them and then hinge on that for update or insert.  My approach here is garbage!  MERGE isn't checking the ON clause for a key, it's just comparing all the items.  My original approach in the issue I opened wasn't going to work either, but it was closer to the right track methinks.  Gotta pull something unique out of the replace fields.

Okay drawing board, here I come!

**Comment by erikest** [comment]
Okay, that wasn't so bad after all.  Now the code grabs the primary key and looks for it in the incoming set of fields to use in the ON clause.  If it can't find that, it looks for a unique constraint and tries that.  Weaknesses right now are more than one column in a primary key, or an additional unique constraint that isn't the first one returned being the one that is sent in with the data.  I guess, I can loop through the results of the unique query and find the first match in the $data.. then we'll be down to situations with complex keys not being covered.  That's a fairly edgy case... but... now that I look, I do see some plugins using them.  Sigh, okay, more work to do...

**Comment by erikest** [comment]
Wheew, debugging php is painful.  But I am no php developer.  Please point me in the direction of productive workflow.   Are people using netbeans or visual studio plugins or what?  

I think I maybe might have possibly got it sort of correctish that time perhaps...  confidence in edge case detection dwindling as night sets in..  I think I can make it to shallow water before the [sharks get me](https://xkcd.com/349/)

**Comment by patrickebates** [comment]
I'm not a true PHP developer myself, but it's always been text editors, log files, and trial & error for me.

Like where you're going with this, especially with checking the table for primary keys.

**Comment by erikest** [comment]
okay, so my notepad++, filezilla upload, browser refresh, fiddler, azure sql audit logs technique is as good as it gets huh?  Es lo que es.  :)

This pass, I believe has actually got legs.  I'm grabbing _all_ the fields that come in $data _and_ which also appear in the KEY_USAGE table and comparing all those in the ON statement, so it's not brittle with respect to constraint name.

I wish there was a better test bed to fire at it.  Does Wordpress have anything that runs through and verifies their API against a standard set of tables?  They've got to have something for when they're making modifications to the core...

**Comment by patrickebates** [comment]
We're taking some time to look at what we want to add in before WP 4.6.  Think this is ready for merge into Master at this time?

**Comment by erikest** [comment]
Well, "it works on my end" :)

I have it on staging and have been testing against it since I posted the
last commit.  I've moving it to production shortly, so it seems stable to
me.

I worked through a couple of iterations to arrive at that code, catching
edge cases that I hit.  At this point it uses all the constraint columns
that come in with the request to find a match, so it's hard to imagine it
missing an existing record.

**Pull request merged**
