### PR TITLE
New translations for plugins

### PR DESCRIPTION
**Pull request by KY4U**

### CODE REVIEW

**Comment by patrickebates** [comment]
Thanks again.  Looks good.

Are these new and updated translations for Yoast related to a recent update?  Haven't run across them yet myself, but then I still need to update that plugin too.

**Comment by KY4U** [comment]
I'm not sure if the Yoast changes are related to a plugin update.  I did find that the following code would not catch one of the necessary changes for the Yoast plugin.

`if ( (stristr($query, "SELECT post_type, MAX(post_modified_gmt) AS date FROM") !== FALSE) && (stristr($query, "GROUP BY post_type ORDER BY post_modified_gmt") !== FALSE) ) {
            $query = str_ireplace(
                'ORDER BY post_modified_gmt', 
                'ORDER BY max(post_modified_gmt)', $query);
        }`

I ended up adding a regular expression check which caught the Yoast issue and I made the change from there.

I have several WP sites that, of course, use several different plugins.  With that said I'll be chipping away at the issues and submitting pull requests as I go.

**Comment by KY4U** [comment]
I have a question regarding the use of stristr().  What is the purpose of using stristr() in the following code?

`        if (stristr($query, " && meta_key = ") !== FALSE) {
            $query = str_ireplace(
                ' && meta_key = ', 
                ' AND meta_key = ', $query);
        }`

and here is another example:

`        if (stristr($query, " AS UNSIGNED") !== FALSE) {
            $query = str_ireplace(
                ' AS UNSIGNED', 
                ' AS BIGINT', $query);
        }`

I can understand using stristr() to determine if you were dealing with a particular query.  From there you can perform a specific translation for that query.  But in these cases, it seems unnecessary.  Two function calls are being performed when one would do.  The more function calls, the slower the translations, and subsequent page loads.

**Comment by patrickebates** [comment]
Good points there.  That was written early on to mirror how other parts of the translation file operate (which was borrowed from WP DB Abstraction Layer and modified for use with PN), so there might be several opportunities to optimize performance.

One question worth asking is if stristr performs significantly faster than str_ireplace.  If so, then first checking the need for replacement would be better when you expect to perform the replacement very rarely.

**Comment by KY4U** [comment]
Your question about performance is a good one.  I agree that the use of stristr would also be beneficial for finding a particular query that required _more than one translation_.  In a case like that, multiple str_ireplace calls would not occur if the query was not the one we were looking for.

**Comment by pippercameron** [comment]
On the subject of performance and general architecture, I'd like to see us start to move individual plugin translations out of translations.php and into dedicated files/modules that we only load when those plugins are present and activated.

**Comment by KY4U** [comment]
I totally agree with that approach.  To expand upon the @pippercameron suggestion, translations could be checked if, and only if, the plugin was present and activated.

**Pull request merged**
